version: '2'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www/:/var/www/html/:rw
            - ./config/nginx/conf.d:/etc/nginx/conf.d/:ro
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./logs/nginx/:/var/log/nginx/:rw
        networks:
            - frontend
        depends_on:
            - php7.2
    php7.2:
        build: ./dockerfile/php/
        expose:
            - "9000"
        volumes:
            - ./www/:/var/www/html/:rw
            - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./config/php/php-fpm.d/www.conf:/usr/local/etc/conf.d/www.conf:ro
            - ./config/php/php/conf.d/:/usr/local/etc/php/conf.d/:ro
            - ./logs/php-fpm/:/var/log/php-fpm/:rw
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
        container_name: php7.2
    phpmyadmin:
        build: ./dockerfile/phpmyadmin/
        environment:
            - PMA_HOST=mysql
        ports:
            - "8000:80"
        volumes:
            - ./phpmyadmin-data:/sessions
        depends_on:
            - php7.2
        networks:
            - frontend
            - backend
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./config/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - ./mysql/mysqldata/:/var/lib/mysql/:rw
            - ./logs/mysql/:/var/log/mysql/:rw
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        networks:
            - backend
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
networks:
    frontend:
    backend: